extends:
  - './node_modules/mobify-code-style/es6/mobify-es6.yml'
settings:
  import/extensions: ['.js']
globals:
  process: false
  DEBUG: false
rules:
  camelcase: off
  no-prototype-builtins: 0
  no-useless-constructor: off
  max-len:
   - error
   - 200
   - ignoreComments: true
parser: babel-eslint
